config/routes.rb
Rails.application.routes.draw do
  root to: 'groups#index'
  resources :users, :posts, :groups

end

app/models/group.rb
class Group < ActiveRecord::Base
has_many :user_groups
has_many :users, through: :user_groups
has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :user_groups
has_many :groups, through: :user_groups
has_many :posts
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ActionController::Base

	def index
		@groups = Group.all
	end

	def show
		@group = Group.find(params[:id])
		@users = User.all
    @post = Post.new
	end

end


app/controllers/posts_controller.rb
class PostsController < ActionController::Base
	def index
		@posts = Post.all
	end

  def show
    @post = Post.new
  end

  def create 
    @post = Post.new
    if @post.save
      redirect_to groups_path
    else
      render "groups/index"
    end
  end

  private

  def post_params
    params.require(:post).permit!
  end

end

app/controllers/users_controller.rb
class UsersController < ActionController::Base

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_group.html.erb
<p><%= link_to(group.name, group_path(group)) %></p>

app/views/groups/index.html.erb
<h1>This is the index page for Groups</h1>


<%= render @groups %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>

<%= render 'posts/form' %>

<% @group.posts.each do |post| %>
  <p><%= post.title %></p>
<% end %>

<% @group.users.each do |user|%>
	<p><%= link_to user.name, user_path(user) %></p>
<% end %>

<%= link_to "Back to groups", groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
This is from the application file
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<h3> New post </h3>

<%= form_for @post do |f| %>
  <%= f.label :title, "Title " %><br>
  <%= f.text_field :title %>
  <br>
  <br>

  <%= f.label :description, "Description" %><br>
  <%= f.text_field :description %>

  <br>
  <br>

  <%= f.label :url, "Url " %> <br>
  <%= f.text_field :url %>

<br>

  <%= f.submit "Create" %>

<% end %>

app/views/posts/index.html.erb
<div class="header">

Some info
</div>
<% @posts.each do |post| %>

<%= post.title %> <br>
<%= post.description %>

<%end %>

app/views/users/_user.html.erb

<p><%= link_to(user.name, user_path(user)) %> </p>

app/views/users/index.html.erb
<h1>This is the index page for users</h1>

<%= render @users %>

app/views/users/show.html.erb
<h1><%= @user.name  %></h1>

<% @user.groups.each do |group| %>
	<p><%= link_to(group.name, group_path(group)) %></p>
<%end %>


<%= link_to "Back to users", users_path %>